---

  - name: Create EC2 instance
    ec2:
      key_name: "{{ key_pair_name }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      wait: yes
      count: 1
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      assign_public_ip: yes
      region: "{{ region }}"
      group_id: "{{ sg_id }}"
    register: ec2

  - debug:
      msg: "{{ ec2.instances }}"

  - name: Check ssh access to EC2
    wait_for:
      host: "{{item.public_ip}}"
      port: 22
      delay: 10
      timeout: 300
    with_items: "{{ ec2.instances }}"


  - name: Add the IP to the hosts list
    add_host:
      name: "{{item.public_ip}}"
    with_items: "{{ ec2.instances }}"

  - name: Create file with ec2 instance ids
    copy:
      dest: "/mnt/c/Users/Arshad/PycharmProjects/ami_creation/ec2-instances-ids"
      content: |
        {{ item.id }}
    with_items: "{{ ec2.instances }}"
