---
# vars file for pdg
        key_pair_name: arshad_new
        instance_type: t3.xlarge
        ami_id: ami-0affd4508a5d2481b
        vpc_subnet_id:  subnet-50a20d1d
        vpc_id: vpc-66ae861c
        sg_id: sg-0da13e856efb5bdc5
